export const exampleImagePrompts: string[] = [
  "Tranquil lake at sunset",
  "Snowy mountain peak",
  "Cityscape with skyscrapers",
  "Colorful hot air balloon",
  "Vibrant blooming flower",
  "Peaceful beach with palm trees",
  "Ancient castle on a hill",
  "Sunlit forest",
  "Countryside cottage in fields",
  "Majestic rainforest waterfall",
  "Birds across a vibrant sunset",
  "Cobblestone street in a town",
  "View from a mountaintop",
  "Blooming lavender fields",
  "Autumn leaves in a forest",
  "Bustling traditional market",
  "Misty waterfall in a lush valley",
  "Golden sunset over a desert landscape",
  "Dramatic rocky coastline",
  "Secluded island with palm-fringed beaches",
  "Rustic wooden cabin by a tranquil river",
  "Glistening snow-covered forest",
  "Lush green vineyard on rolling hills",
  "Enchanting foggy forest",
  "Ancient ruins of a civilization",
  "Vivid rainbow over a picturesque landscape",
  "Glistening icebergs in a pristine arctic scene",
  "Magical starry night sky",
  "Mysterious cave entrance in a mountainside",
  "Vibrant fields of sunflowers",
  "Roaring waterfall in a rugged canyon",
  "Quaint village nestled in a valley",
  "Majestic lighthouse by the sea",
  "Peaceful countryside with grazing sheep",
  "Serene lake surrounded by towering mountains",
  "Breathtaking view from a cliff's edge",
  "Vivid display of northern lights",
  "Sunrise casting golden hues over a meadow",
  "Gorgeous cherry blossom trees in bloom"
];
